### PR TITLE
corrección ejemplo R

### PR DESCRIPTION
**Pull request by vlasvlasvlas**
si llaman al paquete readr deberían leer usando dicho paquete.

Es decir seria:

library(readr)
df<-read_csv("doc.csv")

### CODE REVIEW

**Comment by JoaoCarabetta** [comment]
Thanks!

**Comment by vlasvlasvlas** [comment]
> 
> 
> Thanks!

You're welcome! 

Hey: we're building a local Argentinian Open Data COVID Repository here:
https://github.com/SistemasMapache/Covid19arData

It's daily updated. we built this because local official information its only 1 pdf data source and there's no deep geosegmented data.

We'd really appreciate if you can share our daily mantained open data Argentina's COVID19 Repo with others or over BID site / dashboard, 

Thanks! 
👍 

ps: We're also reusing PurpleBooth good README and bid readme ideas :)

**Comment by JoaoCarabetta** [comment]
Nice! Already shared the dataset with the researcher that manage the updates on COVID19 cases.

**Comment by vlasvlasvlas** [comment]
> 
> 
> Nice! Already shared the dataset with the researcher that manage the updates on COVID19 cases.

Thanks!
we would love to collaborate with our dataset on the bid platform :D

**Pull request merged**
